#!/bin/sh

set -e

export LIBVIRT_DEFAULT_URI='lxc:///'

# workaround to debbug #848317/867379 which triggers more likely on ubuntu
systemctl restart libvirtd

XML=debian/tests/smoke-lxc.xml
DOMAIN=sl

cleanup()
{
   if [ -z "$CLEANED_UP" ]; then
     virsh destroy ${DOMAIN}  || true
     virsh undefine ${DOMAIN} || true
     CLEANED_UP=1
   fi
}

try_check_domain()
{
    for _ in $(seq 10); do
        check_domain && return
        sleep 2s
    done
    echo "Known to be unreliable on test infrastructure"
    exit 77
}

check_domain()
{
    rc=0
    virsh list | grep -qs "${DOMAIN}[[:space:]]\+running"
    rc=$((rc+$?))
    virsh lxc-enter-namespace --noseclabel ${DOMAIN} /bin/ls /bin/ls
    rc=$((rc+$?))
    return $rc
}

trap cleanup EXIT

set -x
virt-host-validate lxc || exit 0
virsh capabilities
virsh capabilities | grep -qs 'emulator>/usr/lib/libvirt/libvirt_lxc'
virsh capabilities | grep -qs 'os_type>exe'
virt-xml-validate ${XML}
virsh define ${XML}
rm -f /var/log/libvirt/lxc/sl.log
virsh start ${DOMAIN}
# Check virtlogd is running
grep -qs "starting up" /var/log/libvirt/lxc/sl.log
try_check_domain
# Make sure a restart doesn't termiante the domain
systemctl restart libvirtd
try_check_domain
virsh destroy ${DOMAIN} || true
virsh undefine ${DOMAIN}
CLEANED_UP=1
set +x

echo 'Smoke test of lxc:/// succesful'
exit 0
